import { RootContainer } from "@/components/General/RootContainer";
import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";

const Users: NextPage = () => {
  const { data } = api.users.all.useQuery();
  return (
    <>
      <Head>
        <title>SweetStack - Users</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootContainer>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1>Users</h1>
          {data?.users?.map((user) => (
            <p key={user.id}>{user.fullName}</p>
          ))}
        </div>
      </RootContainer>
    </>
  );
};

export default Users;
